name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_type == 'branch') }}

jobs:
  check-code-format:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir ruff==0.16.10

      - name: Check code style and imports with Ruff
        run: |
          python -m ruff check src/ tests/ e2e-tests/

      - name: Check code format with Ruff
        if: ${{ always() }}
        run: |
          python -m ruff format --check src/ tests/ e2e-tests/

  run-tests:
    environment: CI/CD
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest ]
        python-version: ["3.10", "3.11", "3.12", "3.13",  "3.14"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ubuntu dependency
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Windows dependency
        if: startsWith(matrix.os, 'windows')
        run: |
            choco install ffmpeg -y

      - name: Install module
        run: |
         pip install --no-cache-dir -e .[dev]

      - name: Run tests
        run: |
          make run-tests

      - name: Run e2e tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
      
        run: |
          make install-dependencies-e2e-tests
          make run-e2e-tests

  build-package-and-run-tests:
    environment: CI/CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install wheel twine setuptools

      - name: Build package
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Install package
        run: |
         pip install dist/*.whl

      - name: Run tests
        run: |
          whisper-ctranslate2 e2e-tests/gossos.mp3
